name: Greet New Contributor

on:
  pull_request_target:
    types: [opened]

jobs:
  greet-new-contributor:
    if: github.event.pull_request.author_association == 'FIRST_TIMER' || github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "🎉 Welcome, @${{ github.actor }}! Thanks for your first contribution! 🚀"
