name: Greet New Contributor

on:
  pull_request_target:
    types: [opened]

jobs:
  greet-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "🎉 Welcome, @${{ github.actor }}! Thanks for your contribution! 🚀"
